# Generated by Django 2.1 on 2019-04-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainText', models.CharField(max_length=100)),
                ('subText', models.CharField(max_length=2000)),
                ('ctaText', models.CharField(max_length=50)),
                ('ctaUrl', models.CharField(max_length=500)),
            ],
        ),
    ]
