# Generated by Django 2.1 on 2019-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainText', models.CharField(max_length=1000)),
                ('subText', models.CharField(max_length=2000)),
                ('ctaText', models.CharField(max_length=500)),
                ('ctaUrl', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainText', models.CharField(max_length=1000)),
                ('subText', models.CharField(max_length=2000)),
                ('ctaText', models.CharField(max_length=500)),
                ('ctaUrl', models.CharField(max_length=1000)),
                ('backgroundUrl', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconUrl', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
